[package]
name = "cpu-arm7tdmi"
description = "ARM7TDMI CPU core (GBA, NDS ARM7)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
core-common.workspace = true
savestate.workspace = true
bitflags.workspace = true
tracing.workspace = true
