[package]
name = "harness"
description = "Accuracy test-ROM runner, framebuffer hashing, snapshot tests."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
core-common.workspace = true
system-gb.workspace = true
system-gbc.workspace = true
system-gba.workspace = true
system-nds.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
insta.workspace = true
