[package]
name = "cpu-sm83"
description = "Sharp SM83 CPU core (Game Boy / Game Boy Color)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
core-common.workspace = true
savestate.workspace = true
tracing.workspace = true
